// 操作函数名
export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const CHANGEPSW = 'CHANGEPSW'
export const USERID = 'USERID'
export const MYSELF = 'MYSELF'
export const GROUPLIST = 'GROUPLIST'
export const USERFRIENDLIST = 'USERFRIENDLIST'
export const FRIENDLIST = 'FRIENDLIST'
export const CHATNAME = 'CHATNAME'
